---

resources:
- name: every-1m
  type: time
  source: {interval: 1m}

jobs:
- name: ssl-validity
  plan:
  - get: every-1m
    trigger: true
  - task: check-ssl-validity
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      inputs:
      - name: satta_concourse_test
        path: ./
      run:
        path: sh
        args: [check_SSL_validity.sh]
        dir: satta_concourse_test
