---

resources:
- name: every-1m
  type: time
  source: {interval: 1m}

-name: git-repo
  type: git
  source:
    uri: https://github.com/sattan66/sattan_concourse_test.git


jobs:
- name: ssl-validity
  plan:
  - get: every-1m
    trigger: true
  - get: git-repo
    trigger: true
  - task: check-ssl-validity
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      inputs:
      - name: sattan_concourse_test
        path: ./
      run:
        path: sh
        args: [check_SSL_validity.sh]
        dir: sattan_concourse_test
